//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.ExcelResolver
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    
    
    public class Hero : ScriptableObject, IExcelData
    {
        
        /// <summary>
        /// 英雄
        /// </summary>
        public int id;
        
        /// <summary>
        /// 名称
        /// </summary>
        public string name;
        
        /// <summary>
        /// icon
        /// </summary>
        public string icon;
        
        /// <summary>
        /// 有宠物
        /// </summary>
        public bool has;
        
        /// <summary>
        /// 血量
        /// </summary>
        public int hp;
        
        /// <summary>
        /// 攻击力
        /// </summary>
        public int atk;
        
        /// <summary>
        /// 移速
        /// </summary>
        public float speed;
        
        /// <summary>
        /// 位置
        /// </summary>
        public Vector3 pos;
        
        /// <summary>
        /// 位置
        /// </summary>
        public Vector2 ches;
    }
}
